/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Tuan4;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import DAO_UI.Database;
import oracle.jdbc.OracleTypes;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

/**
 *
 * @author lemin
 */
public class Profile extends javax.swing.JPanel {

    ArrayList<Profile_item> ds_proFile;
    ArrayList<UserItem> ds_User;

    public Profile() {
        initComponents();
        DS_ProFile();
        DS_TableSpace();
        DS_User();
    }

    private void DS_ProFile() {
        try (Connection conn = Database.GetConnection(); CallableStatement cstmt = conn.prepareCall("{call LayDS_ProFile(?)}");) {
            cstmt.registerOutParameter(1, OracleTypes.CURSOR);

            // Thực thi stored procedure
            cstmt.execute();
            boolean hasResults = cstmt.execute();
            ResultSet rs = (ResultSet) cstmt.getObject(1);
            ds_proFile = new ArrayList<>();
           
            while (rs.next()) {
                String profile = rs.getString("PROFILE");
                String name = rs.getString("RESOURCE_NAME");
                String value = rs.getString("LIMIT");
                Profile_item p = new Profile_item(profile, name, value);
                ds_proFile.add(p);
                themvaoCombo(profile);
            }

            // Đóng kết nối và tài nguyên
            rs.close();
            cstmt.close();
            conn.close();

        } catch (Exception e) {
            // Handle any exceptions, log or display error messages
            e.printStackTrace();
        }
    }

    private void DS_TableSpace() {
        try (Connection conn = Database.GetConnection(); CallableStatement cstmt = conn.prepareCall("{call LayDS_DSTableSpace(?)}");) {
            cstmt.registerOutParameter(1, OracleTypes.CURSOR);

            cstmt.execute();
            boolean hasResults = cstmt.execute();
            ResultSet rs = (ResultSet) cstmt.getObject(1);

            while (rs.next()) {
                String tablespace = rs.getString("tablespace_name");
                cbx_tablespace.addItem(tablespace);
            }

            // Đóng kết nối và tài nguyên
            rs.close();
            cstmt.close();
            conn.close();

        } catch (Exception e) {
            // Handle any exceptions, log or display error messages
            e.printStackTrace();
        }
    }

    private void DS_User() {
        try (Connection conn = Database.GetConnection(); CallableStatement cstmt = conn.prepareCall("{call LayDS_DSUser(?)}");) {
            cstmt.registerOutParameter(1, OracleTypes.CURSOR);

            cstmt.execute();
            boolean hasResults = cstmt.execute();
            ResultSet rs = (ResultSet) cstmt.getObject(1);
            ds_User = new ArrayList<>();
            cbx_User.removeAllItems();
            while (rs.next()) {
                String USERNAME = rs.getString("USERNAME");
                String Df_tablespace = rs.getString("DEFAULT_TABLESPACE");
                String ProFile = rs.getString("PROFILE");
                UserItem item = new UserItem(USERNAME, Df_tablespace, ProFile);
                ds_User.add(item);
            }
            DefaultComboBoxModel box = (DefaultComboBoxModel) cbx_User.getModel();
            box.addAll(ds_User);
            cbx_User.setModel(box);
            rs.close();
            cstmt.close();
            conn.close();

        } catch (Exception e) {
            // Handle any exceptions, log or display error messages
            e.printStackTrace();
        }
    }

    public void themvaoCombo(String name) {
        if (cbx_DSProFile.getItemCount() == 0) {
            cbx_DSProFile.addItem(name);
            return;
        }
        for (int i = 0; i < cbx_DSProFile.getItemCount(); i++) {
            Object item = cbx_DSProFile.getItemAt(i);
            if (name.equalsIgnoreCase(item.toString()) == true) {
                return;
            }

        }
        cbx_DSProFile.addItem(name);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	setBounds(0, 0, 1264, 776);
        setLayout(null);
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbx_User = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Quota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        cbx_tablespace = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbx_DSProFile = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbx_TTProFile = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_GiaTri = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_profilename = new javax.swing.JTextField();
        btn_Sua = new javax.swing.JButton();

        jLabel1.setText("Profile");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin User"));

        jLabel2.setText("Danh sách");

        cbx_User.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_UserItemStateChanged(evt);
            }
        });

        jLabel3.setText("tablespace");

        jLabel4.setText("Quota");

        txt_Quota.setText("jTextField2");

        jLabel5.setText("User Name");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(4, 4, 4)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbx_User, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Quota, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txt_UserName)
                            .addComponent(cbx_tablespace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_them)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbx_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbx_tablespace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Quota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addComponent(btn_them)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin Profile"));

        jLabel6.setText("Danh sách profile");

        cbx_DSProFile.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_DSProFileItemStateChanged(evt);
            }
        });

        jLabel7.setText("Thông tin profile");

        cbx_TTProFile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_TTProFile.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_TTProFileItemStateChanged(evt);
            }
        });

        jLabel8.setText("Giá trị");

        txt_GiaTri.setText("jTextField4");

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        jLabel9.setText("jLabel9");

        txt_profilename.setText("jTextField5");

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(txt_GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(btn_Them)
                            .addComponent(jLabel9))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbx_DSProFile, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbx_TTProFile, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_profilename, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                            .addComponent(btn_Sua))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbx_DSProFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txt_profilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbx_TTProFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Sua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        			.addGap(35))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(310)
        			.addComponent(jLabel1)
        			.addContainerGap(924, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addGap(51)
        					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        					.addGap(15)
        					.addComponent(jLabel1)
        					.addGap(29)
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 668, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
    	try (Connection conn = Database.GetConnection(); CallableStatement callableStatement = conn.prepareCall("{ ? = call DAT_ADMIN.KiemTra_UserTonTai(?) }");) {
    		String UserName = txt_UserName.getText(); 
    		callableStatement.registerOutParameter(1, Types.BOOLEAN);
            // Thiết lập tham số đầu vào
            callableStatement.setString(2, UserName);
            // Thực thi hàm
            callableStatement.execute();
            // Lấy kết quả trả về từ hàm
            boolean userExists = callableStatement.getBoolean(1);
            if (userExists == true) {
                JOptionPane.showMessageDialog(null, "Tài khoản đã tồn tại", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            	} 
    		}catch (Exception e) {
    	            // Handle any exceptions, log or display error messages
    	       e.printStackTrace();
            }
        try (Connection conn = Database.GetConnection(); CallableStatement cstmt = conn.prepareCall("{call add_user_1(?,?,?,?)}")) {
            String UserName = txt_UserName.getText();
            String tablesapce = cbx_tablespace.getSelectedItem().toString();
            String profile = cbx_DSProFile.getSelectedItem().toString();
            String quota = txt_Quota.getText();
            cstmt.setString(1, UserName);
            cstmt.setString(2, tablesapce);
            cstmt.setInt(3, Integer.parseInt(quota));
            cstmt.setString(4, profile);
            cstmt.execute();
            DS_User();
            JOptionPane.showMessageDialog(null, "Thêm thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        try (Connection conn = Database.GetConnection(); CallableStatement cstmt = conn.prepareCall("{? = call pkg_add_profile.main_add_profile(?)}")) {
            cstmt.registerOutParameter(1, Types.BOOLEAN);
            cstmt.setString(2, txt_profilename.getText());
            cstmt.execute();
            boolean k = cstmt.getBoolean(1);
            
            if (k == true) {
                cbx_DSProFile.removeAll();
                DS_ProFile();
                JOptionPane.showMessageDialog(this, "Tạo thành công");
            } else {
            	JOptionPane.showMessageDialog(this, "Tạo thất bại");
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void cbx_DSProFileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_DSProFileItemStateChanged
        String profile = cbx_DSProFile.getSelectedItem().toString();
        DefaultComboBoxModel boxModel = new DefaultComboBoxModel();
        for (Profile_item p : ds_proFile) {
            if (p.profile.equals(profile)) {
                boxModel.addElement(p);
            }
        }
        cbx_TTProFile.setModel(boxModel);
    }//GEN-LAST:event_cbx_DSProFileItemStateChanged

    private void cbx_TTProFileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_TTProFileItemStateChanged
        Profile_item p = (Profile_item) cbx_TTProFile.getSelectedItem();
        txt_GiaTri.setText(p.value);
    }//GEN-LAST:event_cbx_TTProFileItemStateChanged

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        try (Connection conn = Database.GetConnection(); CallableStatement stmt = conn.prepareCall("{call alter_profile(?,?) }");) {
            String profile = cbx_DSProFile.getSelectedItem().toString();
            String value = txt_GiaTri.getText();
            String name = cbx_TTProFile.getSelectedItem().toString() + " " + value;
            stmt.setString(1, profile);
            stmt.setString(2, name);

            stmt.execute();
            System.out.println("Sửa thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void cbx_UserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_UserItemStateChanged
        UserItem item = (UserItem) cbx_User.getSelectedItem();
        cbx_tablespace.setSelectedItem(item.De_Tablespace);
        cbx_DSProFile.setSelectedItem(item.profile);
    }//GEN-LAST:event_cbx_UserItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_them;
    private javax.swing.JComboBox<String> cbx_DSProFile;
    private javax.swing.JComboBox<String> cbx_TTProFile;
    private javax.swing.JComboBox<String> cbx_User;
    private javax.swing.JComboBox<String> cbx_tablespace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_GiaTri;
    private javax.swing.JTextField txt_Quota;
    private javax.swing.JTextField txt_UserName;
    private javax.swing.JTextField txt_profilename;
    // End of variables declaration//GEN-END:variables
}
